### ISSUE TITLE
Canvas Log Viewer utility does not work with refactored operators

### ISSUE THREAD

**Issue by ferenc-hechler** [tmforum-oda/oda-canvas#399]
## Long story short

Following the description in 
https://github.com/tmforum-oda/oda-canvas/tree/main/source/utilities/canvas-log-viewer#canvas-log-viewer-utility

I installed the Canvas Log Viewer Utility.
When executing it, it fails with an error message.

## Description

The documentation needs to be updated in two points:

1. I needed sudo permissions in the npm install: `sudo npm install @lesterthomas/kubectl-canvas_logs -g`
2. to get the component-operator the selector should now be "component-operator instead of "oda-controller": `kubectl get pods --selector app=component-operator -n canvas`

But that is not the issue. I installed a component and wanted to get the logs with the following command:

```
```
$ kubectl canvas-logs demo-a-productcatalogmanagement $POD

=================================================
===           ODA Canvas Log Viewer           ===
=================================================
targetComponent: demo-a-productcatalogmanagement
(node:44880) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error listing pods: TypeError: Cannot read properties of undefined (reading 'metadata')
    at listPods (/usr/lib/node_modules/@lesterthomas/kubectl-canvas_logs/index.js:23:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async mainFunction (/usr/lib/node_modules/@lesterthomas/kubectl-canvas_logs/index.js:47:28)
Canvas Operator: undefined
HttpError: HTTP request failed
    at Request._callback (/usr/lib/node_modules/@lesterthomas/kubectl-canvas_logs/node_modules/@kubernetes/client-node/dist/log.js:42:32)
    at self.callback (/usr/lib/node_modules/@lesterthomas/kubectl-canvas_logs/node_modules/request/request.js:185:22)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/usr/lib/node_modules/@lesterthomas/kubectl-canvas_logs/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:519:28)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/@lesterthomas/kubectl-canvas_logs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  response: <ref *1> IncomingMessage {
    _events: {
      close: [Array],
...
 req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      ...
	  _headerSent: true,
      _closed: false,
      _header: 'GET /api/v1/namespaces/canvas/pods/undefined/log?follow=true&tailLines=500&pretty=false&timestamps=false&container=oda-controller HTTP/1.1\r\n' +
        'Authorization: Bearer eyJh...ucWg\r\n' +
        'host: 10.92.0.1\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      ...
    },
    reason: 'NotFound',
    status: 'Failure'
  },
  statusCode: 404
}	  
```	  

I think the relevant part is:

```
_header: 'GET /api/v1/namespaces/canvas/pods/undefined/log?
  follow=true&tailLines=500&pretty=false&timestamps=false&
  container=oda-controller 
  HTTP/1.1\r\n' +
```

In the same way, as the app label was changed from "oda-controller" to "component-operator" this was also done for the container name.

As I wanted to introspect the secretsmanagementoperator it would be good, if the container name would also be configurable on cli.

**Comment by ferenc-hechler** [comment]
Created an alternative implementation using Pyhon:

https://github.com/tmforum-oda/oda-canvas/tree/feature/320-stardardize-logging-secman-depapi/source/utilities/canvas-log-viewer/python_alternative
